apiVersion: v1
kind: ServiceAccount
metadata:
  name: netcheck-operator-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netcheck-role-cluster
rules:
  # Kopf Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Kopf Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Kopf Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # This could be restricted to our operator namespace
  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: Access to our NetworkAssertions cluster-wide
  # Note we don't create or delete them - that's up to the user.
  - apiGroups: [hardbyte.nz]
    resources: [networkassertions]
    verbs: [list, watch, patch]

  # Application: other resources we produce and manipulate
  # Here, we create and patch CronJobs, Jobs, Pods, configmaps but we don't delete them.
  - apiGroups: [batch, extensions]
    resources: [jobs, cronjobs]
    verbs: [create]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  # We directly create config maps. At some point we may need to patch them.
  - apiGroups: [""]
    resources: [configmaps]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netcheck-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netcheck-role-cluster
subjects:
  - kind: ServiceAccount
    name: netcheck-operator-account
    namespace: netcheck
