apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networkassertions.hardbyte.nz
spec:
  scope: Namespaced
  group: hardbyte.nz
  names:
    kind: NetworkAssertion
    plural: networkassertions
    singular: networkassertion
    shortNames:
      - nas
      - na
  versions:
    - name: v1
      served: true
      storage: true
#      additionalPrinterColumns:
#        - jsonPath:
#          name:
#          type:
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true

