[tool.poetry]
name = "netcheck-operator"
version = "0.1.1"
description = "Netcheck is a cloud native tool for specifying and regularly checking assertions about network conditions. Organisations use netcheck to proactively verify whether security controls are working as intended, alerting them to misconfiguration and potential threats."
authors = ["Brian Thorne <brian@hardbyte.nz>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.10"
kopf = "^1.36.0"
kubernetes = "^25.3.0"
rich = "^12.6.0"
structlog = "^22.3.0"
prometheus-client = "^0.15.0"
pydantic = "^1.10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
