apiVersion: netchecks.io/v1
kind: NetworkAssertion
metadata:
  name: http-should-work
  namespace: default
  annotations:
    description: Assert pod can connect to k8s API
spec:
  schedule: "@hourly"
  rules:
    - name: kubernetes-version
      type: http
      url: https://kubernetes/version
      verify-tls-cert: false
      expected: pass
      validate:
        message: Http request to Kubernetes API should succeed.
    - name: httpbin-service
      type: http
      url: http://httpbin/version
      verify-tls-cert: false
      expected: pass
      validate:
        message: Http request to locally installed httpbin service should succeed.
