apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "netchecks.fullname" . }}
  labels:
    {{- include "netchecks.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "netchecks.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "netchecks.serviceAccountName" . }}
    namespace: '{{ .Release.Namespace }}'
