apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netchecks.fullname" . }}
  labels: {{ include "netchecks.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "probe": {
        "image": {{ .Values.probeConfig.image | toJson }},
        "imagePullSecrets": {{ .Values.probeConfig.imagePullSecrets | toJson }},
        "podAnnotations": {{ .Values.probeConfig.podAnnotations | toJson }}
        }
    }