apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-http-netcheck-sa
  namespace: default
---
apiVersion: hardbyte.nz/v1
kind: NetworkAssertion
metadata:
  name: http-should-work
  namespace: default
  annotations:
    description: Assert pod can connect to k8s API
spec:
  template:
    spec:
      serviceAccountName: test-http-netcheck-sa
      securityContext:
        runAsUser: 1000
    metadata:
      labels:
        optional-label: applied-to-test-pod
      annotations:
        my: override-annotation
  schedule: "@hourly"
  rules:
    - name: kubernetes-version
      type: http
      url: https://kubernetes/version
      verify-tls-cert: false
      expected: pass
      validate:
        message: Http request to Kubernetes API should succeed.
